name = "club-cup-tracker-2025"
compatibility_date = "2024-03-20"
main = "./dist/index.html"

[site]
bucket = "./dist"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
entry-point = "workers-site"
pages_build_output_dir = "dist"
