name = "club-cup-tracker-2025"
compatibility_date = "2024-03-20"

[site]
bucket = "./dist"
pages_build_output_dir = "dist"
zone_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site"
pages_build_output_dir = "dist"
